//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.BooksInterface")]
    public interface BooksInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BooksInterface/conncetToDatabase", ReplyAction="http://tempuri.org/BooksInterface/conncetToDatabaseResponse")]
        void conncetToDatabase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BooksInterface/conncetToDatabase", ReplyAction="http://tempuri.org/BooksInterface/conncetToDatabaseResponse")]
        System.Threading.Tasks.Task conncetToDatabaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BooksInterface/AddBook", ReplyAction="http://tempuri.org/BooksInterface/AddBookResponse")]
        bool AddBook();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BooksInterface/AddBook", ReplyAction="http://tempuri.org/BooksInterface/AddBookResponse")]
        System.Threading.Tasks.Task<bool> AddBookAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BooksInterface/GetBook", ReplyAction="http://tempuri.org/BooksInterface/GetBookResponse")]
        int GetBook(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BooksInterface/GetBook", ReplyAction="http://tempuri.org/BooksInterface/GetBookResponse")]
        System.Threading.Tasks.Task<int> GetBookAsync(int bookId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BooksInterfaceChannel : BookService.ServiceReference1.BooksInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BooksInterfaceClient : System.ServiceModel.ClientBase<BookService.ServiceReference1.BooksInterface>, BookService.ServiceReference1.BooksInterface {
        
        public BooksInterfaceClient() {
        }
        
        public BooksInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BooksInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BooksInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BooksInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void conncetToDatabase() {
            base.Channel.conncetToDatabase();
        }
        
        public System.Threading.Tasks.Task conncetToDatabaseAsync() {
            return base.Channel.conncetToDatabaseAsync();
        }
        
        public bool AddBook() {
            return base.Channel.AddBook();
        }
        
        public System.Threading.Tasks.Task<bool> AddBookAsync() {
            return base.Channel.AddBookAsync();
        }
        
        public int GetBook(int bookId) {
            return base.Channel.GetBook(bookId);
        }
        
        public System.Threading.Tasks.Task<int> GetBookAsync(int bookId) {
            return base.Channel.GetBookAsync(bookId);
        }
    }
}
